const imgData = {
    children: [
        {src:'./images/DSC_2424.jpg', alt: 'children', full_size: './images/DSC_2424.jpg', adjustment: 'img-left-250'},
        {src:'./images/DSC_3096.jpg', alt: 'children', full_size: './images/DSC_3096.jpg', adjustment: ''},
        {src:'./images/DSC_3105.jpg', alt: 'children', full_size: './images/DSC_3105.jpg', adjustment: 'img-left-225 mobile-offset-200'},
        {src:'./images/DSC_3150.jpg', alt: 'children', full_size: './images/DSC_3150.jpg', adjustment: 'img-left-100 mobile-offset-100'},
        {src:'./images/DSC_3278.jpg', alt: 'children', full_size: './images/DSC_3278.jpg', adjustment: 'img-left-150'},
        {src:'./images/DSC_3548.jpg', alt: 'children', full_size: './images/DSC_3548.jpg', adjustment: 'img-left-50 mobile-offset-150'},
        {src:'./images/DSC_3646.jpg', alt: 'children', full_size: './images/DSC_3646.jpg', adjustment: 'img-left-225 mobile-offset-175'},
        {src:'./images/DSC_3695.jpg', alt: 'children', full_size: './images/DSC_3695.jpg', adjustment: 'img-left-300'},
        {src:'./images/DSC_3761.jpg', alt: 'children', full_size: './images/DSC_3761.jpg', adjustment: 'img-left-225 mobile-offset-200'},
        {src:'./images/DSC_4149.jpg', alt: 'children', full_size: './images/DSC_4149.jpg', adjustment: 'img-left-275'},
        {src:'./images/DSC_4478.jpg', alt: 'children', full_size: './images/DSC_4478.jpg', adjustment: 'img-left-50 mobile-offset-150'},
        {src:'./images/DSC_4501.jpg', alt: 'children', full_size: './images/DSC_4501.jpg', adjustment: 'img-left-300 mobile-offset-250'},
        {src:'./images/DSC_4504.jpg', alt: 'children', full_size: './images/DSC_4504.jpg', adjustment: 'img-left-300 mobile-offset-200'},
        {src:'./images/DSC_4536.jpg', alt: 'children', full_size: './images/DSC_4536.jpg', adjustment: 'mobile-offset-100'},
        {src:'./images/DSC_4558.jpg', alt: 'children', full_size: './images/DSC_4558.jpg', adjustment: 'mobile-offset-150'},
        {src:'./images/DSC_4559.jpg', alt: 'children', full_size: './images/DSC_4559.jpg', adjustment: 'mobile-offset-150'},
        {src:'./images/DSC_4620.jpg', alt: 'children', full_size: './images/DSC_4620.jpg', adjustment: 'img-left-200'},
        {src:'./images/DSC_4644.jpg', alt: 'children', full_size: './images/DSC_4644.jpg', adjustment: 'img-left-200'},
        {src:'./images/DSC_4745.jpg', alt: 'children', full_size: './images/DSC_4745.jpg', adjustment: 'mobile-offset-150'},
        {src:'./images/DSC_4747.jpg', alt: 'children', full_size: './images/DSC_4747.jpg', adjustment: 'img-left-200'},
        {src:'./images/DSC_5015.jpg', alt: 'children', full_size: './images/DSC_5015.jpg', adjustment: 'img-left-325'},
        {src:'./images/DSC_5020-2.jpg', alt: 'children', full_size: './images/DSC_5020-2.jpg', adjustment: 'img-left-325'},
        {src:'./images/DSC_5037.jpg', alt: 'children', full_size: './images/DSC_5037.jpg', adjustment: 'img-left-200 mobile-offset-100'},
        {src:'./images/DSC_5715.jpg', alt: 'children', full_size: './images/DSC_5715.jpg', adjustment: 'img-left-175 mobile-offset-125'},
        {src:'./images/DSC_8195.jpg', alt: 'children', full_size: './images/DSC_8195.jpg', adjustment: 'img-left-50 mobile-offset-100'},
        {src:'./images/DSC_9122.jpg', alt: 'children', full_size: './images/DSC_9122.jpg', adjustment: 'img-left-150 mobile-offset-125'},
        {src:'./images/DSC_9145.jpg', alt: 'children', full_size: './images/DSC_9145.jpg', adjustment: 'img-left-200 mobile-offset-175'},
        {src:'./images/Kowalick_19.jpg', alt: 'children', full_size: './images/Kowalick_19.jpg', adjustment: 'mobile-offset-50'},
        {src:'./images/Kowalick_27.jpg', alt: 'children', full_size: './images/Kowalick_27.jpg', adjustment: 'img-left-75 mobile-offset-50'},
        {src:'./images/Kowalick_34.jpg', alt: 'children', full_size: './images/Kowalick_34.jpg', adjustment: ''},
        {src:'./images/NPG_1778.jpg', alt: 'children', full_size: './images/NPG_1778.jpg', adjustment: 'img-left-150 mobile-offset-100'},
        {src:'./images/NPG_2335.jpg', alt: 'children', full_size: './images/NPG_2335.jpg', adjustment: 'img-left-200 mobile-offset-150'},
    ],
    couples: [
        {src:'./images/DSC_1605.jpg', alt: 'couples', full_size: './images/DSC_1605.jpg', adjustment: 'img-left-225 mobile-offset-200'},
        {src:'./images/DSC_1697.jpg', alt: 'couples', full_size: './images/DSC_1697.jpg', adjustment: 'img-left-50 mobile-offset-150'},
        {src:'./images/DSC_1788.jpg', alt: 'couples', full_size: './images/DSC_1788.jpg', adjustment: 'img-left-300 mobile-offset-250'},
        {src:'./images/DSC_1827.jpg', alt: 'couples', full_size: './images/DSC_1827.jpg', adjustment: 'img-left-175 mobile-offset-150'},
        {src:'./images/DSC_1897.jpg', alt: 'couples', full_size: './images/DSC_1897.jpg', adjustment: 'img-left-200 mobile-offset-150'},
        {src:'./images/DSC_1932-2.jpg', alt: 'couples', full_size: './images/DSC_1932-2.jpg', adjustment: 'img-left-50 mobile-offset-200'},
        {src:'./images/DSC_1978.jpg', alt: 'couples', full_size: './images/DSC_1978.jpg', adjustment: 'img-left-250'},
        {src:'./images/DSC_2417.jpg', alt: 'couples', full_size: './images/DSC_2417.jpg', adjustment: 'img-left-250 mobile-offset-200'},
        {src:'./images/DSC_2472.jpg', alt: 'couples', full_size: './images/DSC_2472.jpg', adjustment: 'img-left-250 mobile-offset-200'},
        {src:'./images/DSC_2512.jpg', alt: 'couples', full_size: './images/DSC_2512.jpg', adjustment: 'img-left-325 mobile-offset-275'},
        {src:'./images/DSC_2665.jpg', alt: 'couples', full_size: './images/DSC_2665.jpg', adjustment: 'mobile-offset-150'},
        {src:'./images/DSC_2838.jpg', alt: 'couples', full_size: './images/DSC_2838.jpg', adjustment: 'img-left-250'},
        {src:'./images/DSC_2922.jpg', alt: 'couples', full_size: './images/DSC_2922.jpg', adjustment: 'img-left-325'},
        {src:'./images/DSC_2969.jpg', alt: 'couples', full_size: './images/DSC_2969.jpg', adjustment: 'img-left-300 mobile-offset-250'},
        {src:'./images/DSC_4709.jpg', alt: 'couples', full_size: './images/DSC_4709.jpg', adjustment: 'img-left-150 mobile-offset-100'},
        {src:'./images/DSC_4838.jpg', alt: 'couples', full_size: './images/DSC_4838.jpg', adjustment: 'img-left-225 mobile-offset-200'},
        {src:'./images/DSC_8276-2.jpg', alt: 'couples', full_size: './images/DSC_8276-2.jpg', adjustment: 'img-left-50 mobile-offset-150'},
        {src:'./images/DSC_8287.jpg', alt: 'couples', full_size: './images/DSC_8287.jpg', adjustment: 'img-left-150 mobile-offset-125'},
        {src:'./images/DSC_8821.jpg', alt: 'couples', full_size: './images/DSC_8821.jpg', adjustment: 'img-left-50 mobile-offset-100'},
        {src:'./images/DSC_9025.jpg', alt: 'couples', full_size: './images/DSC_9025.jpg', adjustment: 'img-left-300 mobile-offset-325'},
        {src:'./images/NG006.jpg', alt: 'couples', full_size: './images/NG006.jpg', adjustment: 'img-left-200 mobile-offset-150'},
        {src:'./images/NG009.jpg', alt: 'couples', full_size: './images/NG009.jpg', adjustment: 'img-left-225 mobile-offset-200'},
        {src:'./images/NG047.jpg', alt: 'couples', full_size: './images/NG047.jpg', adjustment: 'img-left-275 mobile-offset-250'},
        {src:'./images/NG063.jpg', alt: 'couples', full_size: './images/NG063.jpg', adjustment: 'mobile-offset-100'},
        {src:'./images/NG080.jpg', alt: 'couples', full_size: './images/NG080.jpg', adjustment: 'mobile-offset-100'},
        {src:'./images/NG087.jpg', alt: 'couples', full_size: './images/NG087.jpg', adjustment: 'img-left-150 mobile-offset-100'},
        {src:'./images/NG101.jpg', alt: 'couples', full_size: './images/NG101.jpg', adjustment: 'img-left-125 mobile-offset-100'},
        {src:'./images/NPG_1219.jpg', alt: 'couples', full_size: './images/NPG_1219.jpg', adjustment: 'img-left-175 mobile-offset-150'},
        {src:'./images/NPG_3226.jpg', alt: 'couples', full_size: './images/NPG_3226.jpg', adjustment: 'img-left-250'},
        {src:'./images/NPG_3236.jpg', alt: 'couples', full_size: './images/NPG_3236.jpg', adjustment: 'img-left-200'},
        {src:'./images/NPG_3264.jpg', alt: 'couples', full_size: './images/NPG_3264.jpg', adjustment: 'img-left-200 mobile-offset-175'},
        {src:'./images/NPG_3314.jpg', alt: 'couples', full_size: './images/NPG_3314.jpg', adjustment: 'img-left-200'},
        {src:'./images/NPG_3358.jpg', alt: 'couples', full_size: './images/NPG_3358.jpg', adjustment: 'img-left-300'},
        {src:'./images/NPG_3394.jpg', alt: 'couples', full_size: './images/NPG_3394.jpg', adjustment: 'img-left-250'},
        {src:'./images/NPG_3455.jpg', alt: 'couples', full_size: './images/NPG_3455.jpg', adjustment: 'img-left-250 mobile-offset-225'},
        {src:'./images/NPG_3541.jpg', alt: 'couples', full_size: './images/NPG_3541.jpg', adjustment: 'img-left-150'},
        {src:'./images/NPG_3569.jpg', alt: 'couples', full_size: './images/NPG_3569.jpg', adjustment: 'img-left-150 mobile-offset-125'},
        {src:'./images/NPG_3622.jpg', alt: 'couples', full_size: './images/NPG_3622.jpg', adjustment: 'img-left-50 mobile-offset-100'},
        {src:'./images/NPG_3695.jpg', alt: 'couples', full_size: './images/NPG_3695.jpg', adjustment: 'img-left-225 mobile-offset-200'},
        {src:'./images/NPG_4589.jpg', alt: 'couples', full_size: './images/NPG_4589.jpg', adjustment: 'img-left-125 mobile-offset-75'},
        {src:'./images/NPG_4610.jpg', alt: 'couples', full_size: './images/NPG_4610.jpg', adjustment: 'img-left-175'}
    ],
    senior: [
        {src:'./images/DSC_3385.jpg', alt: 'senior', full_size: './images/DSC_3385.jpg', adjustment: 'img-left-175 mobile-offset-150'},
        {src:'./images/DSC_3455.jpg', alt: 'senior', full_size: './images/DSC_3455.jpg', adjustment: 'img-left-50 mobile-offset-200'},
        {src:'./images/DSC_3629.jpg', alt: 'senior', full_size: './images/DSC_3629.jpg', adjustment: 'mobile-offset-100'},
        {src:'./images/DSC_4093-2.jpg', alt: 'senior', full_size: './images/DSC_4093-2.jpg', adjustment: 'mobile-offset-100'},
        {src:'./images/DSC_4093.jpg', alt: 'senior', full_size: './images/DSC_4093.jpg', adjustment: 'mobile-offset-100'},
        {src:'./images/DSC_4120.jpg', alt: 'senior', full_size: './images/DSC_4120.jpg', adjustment: 'mobile-offset-125'},
        {src:'./images/DSC_4264.jpg', alt: 'senior', full_size: './images/DSC_4264.jpg', adjustment: 'img-left-200'},
        {src:'./images/DSC_4325.jpg', alt: 'senior', full_size: './images/DSC_4325.jpg', adjustment: 'mobile-offset-150'},
        {src:'./images/DSC_4330.jpg', alt: 'senior', full_size: './images/DSC_4330.jpg', adjustment: 'img-left-200'},
        {src:'./images/DSC_4352.jpg', alt: 'senior', full_size: './images/DSC_4352.jpg', adjustment: 'img-left-200'},
        {src:'./images/DSC_4369-2.jpg', alt: 'senior', full_size: './images/DSC_4369-2.jpg', adjustment: 'img-left-100'},
        {src:'./images/DSC_4503.jpg', alt: 'senior', full_size: './images/DSC_4503.jpg', adjustment: 'img-left-50 mobile-offset-100'},
        {src:'./images/DSC_4530.jpg', alt: 'senior', full_size: './images/DSC_4530.jpg', adjustment: 'mobile-offset-125'},
        {src:'./images/DSC_4764.jpg', alt: 'senior', full_size: './images/DSC_4764.jpg', adjustment: 'img-left-200'},
        {src:'./images/DSC_8362.jpg', alt: 'senior', full_size: './images/DSC_8362.jpg', adjustment: 'img-left-200 mobile-offset-150'},
        {src:'./images/Laura_21.jpg', alt: 'senior', full_size: './images/Laura_21.jpg', adjustment: 'img-left-150 mobile-offset-125'},
        {src:'./images/Laura_34.jpg', alt: 'senior', full_size: './images/Laura_34.jpg', adjustment: 'img-left-200 mobile-offset-175'},
        {src:'./images/Laura_40.jpg', alt: 'senior', full_size: './images/Laura_40.jpg', adjustment: 'mobile-offset-75'},
        {src:'./images/NPG_2586.jpg', alt: 'senior', full_size: './images/NPG_2586.jpg', adjustment: 'img-left-75 mobile-offset-50'},
        {src:'./images/NPG_2685.jpg', alt: 'senior', full_size: './images/NPG_2685.jpg', adjustment: 'img-left-125 mobile-offset-100'},
        {src:'./images/NPG_2739.jpg', alt: 'senior', full_size: './images/NPG_2739.jpg', adjustment: 'img-left-175'},
        {src:'./images/NPG_2773.jpg', alt: 'senior', full_size: './images/NPG_2773.jpg', adjustment: 'img-left-50 mobile-offset-75'},
        {src:'./images/NPG_2794.jpg', alt: 'senior', full_size: './images/NPG_2794.jpg', adjustment: 'img-left-50 mobile-offset-50'},
        {src:'./images/NPG_2810.jpg', alt: 'senior', full_size: './images/NPG_2810.jpg', adjustment: 'img-left-50 mobile-offset-50'},
        {src:'./images/NPG_3722.jpg', alt: 'senior', full_size: './images/NPG_3722.jpg', adjustment: 'img-left-200 mobile-offset-150'},
        {src:'./images/NPG_3744.jpg', alt: 'senior', full_size: './images/NPG_3744.jpg', adjustment: 'img-left-100'},
        {src:'./images/NPG_3750.jpg', alt: 'senior', full_size: './images/NPG_3750.jpg', adjustment: 'img-left-150'},
        {src:'./images/NPG_3953.jpg', alt: 'senior', full_size: './images/NPG_3953.jpg', adjustment: 'img-left-50 mobile-offset-100'},
        {src:'./images/NPG_3991.jpg', alt: 'senior', full_size: './images/NPG_3991.jpg', adjustment: 'img-left-200 mobile-offset-100'},
        {src:'./images/NPG_4073.jpg', alt: 'senior', full_size: './images/NPG_4073.jpg', adjustment: 'img-left-200 mobile-offset-100'}
    ],
    weddings: [
        {src:'./images/DSC_9453-2.jpg', alt: 'weddings', full_size: './images/DSC_9453-2.jpg', adjustment: 'img-left-75 mobile-offset-25'},
        {src:'./images/Wolg0204bw.jpg', alt: 'weddings', full_size: './images/Wolg0204bw.jpg', adjustment: 'img-left-300'},
        {src:'./images/Wolg0245bw.jpg', alt: 'weddings', full_size: './images/Wolg0245bw.jpg', adjustment: 'img-left-150 mobile-offset-100'},
        {src:'./images/Wolg0385.jpg', alt: 'weddings', full_size: './images/Wolg0385.jpg', adjustment: 'img-left-150 mobile-offset-75'},
        {src:'./images/Wolg0644.jpg', alt: 'weddings', full_size: './images/Wolg0644.jpg', adjustment: 'img-left-150 mobile-offset-125'},
        {src:'./images/Wolg0653.jpg', alt: 'weddings', full_size: './images/Wolg0653.jpg', adjustment: 'img-left-250 mobile-offset-200'},
        {src:'./images/Wolg0662.jpg', alt: 'weddings', full_size: './images/Wolg0662.jpg', adjustment: 'img-left-200 mobile-offset-175'}
    ]
}